version: "3.6"
services:
  iris:
    build: .
    restart: always
    ports:
      - "1972:51773"
      - ${IRIS_PORT}:52773
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
      - ./src/csp:/opt/irisapp/csp
